apiVersion: v1
kind: Service

metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 23000
    targetPort: web
  selector:
    app: grafana
