apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: redis-cluster-metrics
  labels:
    k8s-app: redis-cluster
spec:
  selector:
    app: redis-cluster
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 9121
    targetPort: 9121
    protocol: TCP
