apiVersion: v1
kind: Service
metadata:
  namespace: mysql
  name: mariadb-cluster-metrics
  labels:
    k8s-app: mariadb-cluster
spec:
  selector:
    app: mariadb
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 9104
    targetPort: 9104
    protocol: TCP
