apiVersion: v1
kind: Endpoints
metadata:
  name: etcd-k8s
  namespace: kube-system
  labels:
    k8s-app: etcd
subsets:
- addresses:
  - ip: 172.17.0.85
    nodeName: etcd1
  - ip: 172.17.0.86
    nodeName: etcd2
  - ip: 172.17.0.87
    nodeName: etcd3
  ports:
  - name: api
    port: 2379
    protocol: TCP
