apiVersion: v1
kind: Endpoints
metadata:
  namespace: monitoring
  name: kube-scheduler
  labels:
    k8s-app: kube-scheduler
subsets:
- addresses:
  - ip: 172.17.0.85
    nodeName: by-master01
  - ip: 172.17.0.86
    nodeName: by-master02
  - ip: 172.17.0.87
    nodeName: by-master03
  ports:
  - name: http-metrics
    port: 10251
    protocol: TCP
